<?xml version="1.0"?>
<package format="3">
  <name>questix_msgs</name>
  <version>3.0.0</version>
  <description>Common message definitions for QUESTiX, including the unified emergency stop interface.</description>
  <maintainer email="aki.grade2580@outlook.jp">asa-naki</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>std_msgs</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
