cmake_minimum_required(VERSION 3.8)
project(questix_control_config)
find_package(ament_cmake_auto REQUIRED)
find_package(ament_cmake_python REQUIRED)
ament_auto_find_build_dependencies()
ament_python_install_package(${PROJECT_NAME})
install(FILES README.md DESTINATION share/${PROJECT_NAME})
ament_auto_package(INSTALL_TO_SHARE config launch)
